### ISSUE TITLE
Content Issues

### ISSUE THREAD

**Issue by medthol** [LamTechConsult/nraprod#5]
Cannot edit the Board of Directors and Management articles. We want to follow the blue color sub heading you have been using on some pages (for example under department). Can you guide us the specific blue color so as to maintain uniformity.

**Comment by click2tman** [comment]
You need to use the **People Profile** Content Type to create profiles for each *Board Member, Senior Management Team Member and other Staff** Board, and Management pages are dynamically generated using a view. You don't have direct access to edit those pages as Publisher but you do have access to create the content that is displayed in those pages.  See my screen shots below

![screen shot 2015-01-02 at 9 22 27 am](https://cloud.githubusercontent.com/assets/1200007/5596727/5e6effa2-9263-11e4-92bc-7f5261372521.png)

![screen shot 2015-01-02 at 9 23 22 am](https://cloud.githubusercontent.com/assets/1200007/5596728/627813b8-9263-11e4-892a-ef9e63b11fa5.png)

![screen shot 2015-01-02 at 9 23 28 am](https://cloud.githubusercontent.com/assets/1200007/5596729/67360022-9263-11e4-81ff-dba55d546b36.png)
![screen shot 2015-01-02 at 9 23 35 am](https://cloud.githubusercontent.com/assets/1200007/5596730/69c47300-9263-11e4-85cc-b318e25a1e3e.png)
![screen shot 2015-01-02 at 9 23 42 am](https://cloud.githubusercontent.com/assets/1200007/5596731/6be229f2-9263-11e4-97b5-5d4d2c5761ab.png)
![screen shot 2015-01-02 at 9 23 53 am](https://cloud.githubusercontent.com/assets/1200007/5596733/700c9936-9263-11e4-8f78-7589c87e6e85.png)
![screen shot 2015-01-02 at 9 24 32 am](https://cloud.githubusercontent.com/assets/1200007/5596734/7386af70-9263-11e4-8e05-39aea313debf.png)
